[workspace]
authors = ["Cameron Riddell <cameron@dutc.io>"]
channels = ["conda-forge"]
name = "2025-12-09_BasicProfilingforResearchCode"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = ">=2.3.5,<3"
hyperfine = ">=1.20.0,<2"
