[workspace]
authors = ["Cameron Riddell <cameron@dutc.io>"]
channels = ["conda-forge"]
name = "2025-12-09_BasicProfilingforResearchCode"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pandas = ">=2.3.3,<3"
polars = ">=1.35.2,<2"
numpy = ">=2.3.5,<3"
matplotlib = ">=3.10.8,<4"
hyperfine = ">=1.20.0,<2"
jupyterlab = ">=4.5.0,<5"
